# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/measurementsdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================
  jpa:
    show-sql: true #false
    generate-ddl: true #false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  main:
    allow-bean-definition-overriding: true